config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  root to: 'imagings#index'
  resources :imagings do
    collection do
      match 'search', via: [:get, :post]
    end
    resources :conditions, only: [:new, :create, :show, :edit, :update, :destroy] do
      member do
        put 'toggle_checkbox'
      end
      collection do
        delete 'destroy_selected'
      end
    end
    resources :remarks, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :users, only: :show
  resources :occupations do
    resources :machines, only: [:new, :create, :show, :edit, :update, :destroy]
    resources :occupation_memberships, only: [:index, :new, :show, :create, :destroy] do
      member do
        patch 'accept'
        patch 'reject'
      end
    end
    collection do
      get :search
    end
  end
  post '/occupations/search', to: 'occupations#search'
  delete 'occupations/:id/leave', to: 'occupations#leave', as: :leave_occupation

  resources :contacts, only: [:index, :new, :create, :destroy] do
    patch :update_visibility, on: :collection
  end
  get 'contact_thanks', to: 'contacts#thanks', as: 'contact_thanks'

  #resources :categories, only: [:index, :new, :create]
  #get '/category/:id', to: 'categories#search'
end

app/models/imaging.rb
class Imaging < ApplicationRecord
  has_many :conditions, dependent: :destroy
  has_many :imaging_heights, dependent: :destroy
  has_many :heights, through: :imaging_heights, dependent: :destroy
  has_many :imaging_middles, dependent: :destroy
  has_many :middles, through: :imaging_middles, dependent: :destroy
  has_many :imaging_lows, dependent: :destroy
  has_many :lows, through: :imaging_lows, dependent: :destroy
  has_one  :remark, dependent: :destroy

  accepts_nested_attributes_for :imaging_heights

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :site
  with_options presence: true do
    validates :site_id
    validates :purpose
  end

  validate :unique_site_id_with_same_purpose

  def unique_site_id_with_same_purpose
    if self.class.where(site_id: site_id, purpose: purpose).where.not(id: id).exists?
      errors.add(:site_id, "can only have one record with the same purpose")
    end
  end


  def self.search_by_heights_lows(height_ids, low_ids)
    if height_ids.present? || low_ids.present?
      joins(:heights, :lows)
        .where(imaging_heights: { height_id: height_ids })
        .where(imaging_lows: { low_id: low_ids })
    else
      includes(:heights, :lows)
    end
  end
end

app/controllers/imagings_controller.rb
class ImagingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_imaging, only: [:edit, :update, :destroy]
  before_action :set_search, only: [:new, :edit]
  skip_before_action :set_search_query, only: [:search]

  def index
    @occupation = current_user.occupation || Occupation.find_by(name: "未登録")
  end
  
  def new  
    if current_user.occupation.id == 2
      redirect_to imaging_path(@imaging)
    else
      @occupation = current_user.occupation
      @imaging = Imaging.new
    end
  end
  

  def create
    @occupation = current_user.occupation || Occupation.find_by(name: "未登録")
    @imaging = Imaging.new(imaging_params)
    if @imaging.save
    flash[:success] = "新規登録が完了しました。"
      redirect_to imaging_path(@imaging, occupation_id: current_user.occupation.id)
    else
      render :new
    end
  end

  def show
    @occupation_id = params[:occupation_id]
    @users = User.where(occupation_id: @occupation_id)
    @imaging = Imaging.find(params[:id])
    @condition = @imaging.conditions.build
    @occupation = Occupation.find_by(id: @occupation_id) || Occupation.find_by(name: "未登録")
    @occupations = Occupation.includes(:conditions).where(conditions: {imaging_id: @imaging.id}) || Occupation.find_by(name: "未登録")
    @remark = Remark.find_by(imaging_id: @imaging.id, occupation_id: @occupation.id)
  end

  def edit
    if current_user.occupation.present?
      @occupation = current_user.occupation
    else
      redirect_to imaging_path(@imaging)
    end
  end

  def update
    @occupation = current_user.occupation
    height_ids = params[:imaging][:height_ids] || [] 
    low_ids = params[:imaging][:low_ids] || [] 
    @imaging.height_ids = params[:imaging][:height_ids]
    @imaging.low_ids = params[:imaging][:low_ids]
    if @imaging.update(imaging_params)
      redirect_to imaging_path(@imaging, occupation_id: current_user.occupation.id)
    else
      render :edit
    end
  end

  def destroy
    @imaging.destroy 
    redirect_to root_path
  end

  def search
    @occupation_id = params[:occupation_id]
    @occupation = current_user.occupation || Occupation.find_by(name: "未登録")
    @search_occupation = Occupation.find_by(id: @occupation_id)
    @heights = Height.all
    @lows = Low.all

    height_ids = params[:height_ids]&.split(',') || []
    low_ids = params[:low_ids]&.split(',') || []

    @search_imagings = Imaging.search_by_heights_lows(height_ids, low_ids).distinct
  
    if height_ids.present? || low_ids.present?
      @search_imagings = @search_imagings.distinct
    end
    
    respond_to do |format|
      format.json { render json: @search_imagings }
      format.html
    end
  end

  private
  def imaging_params
    params.require(:imaging).permit(:site_id, :purpose, :identification, :symptoms, :treatment, :comment, height_ids: [], middle_ids: [], low_ids: [])
  end

  def set_imaging
    @imaging = Imaging.find(params[:id])
  end

  def set_search
    if params[:q]&.dig(:purpose_cont)
      squished_keywords = params[:q][:purpose_cont].squish
      params[:q][:purpose_cont_cont_any] = squished_keywords.split(" ")
    end
  
    session[:search_params] ||= { site_id_eq: nil, purpose_cont: nil }
    session[:search_params].merge!(params[:q]) if params[:q].present?
    @q = Imaging.ransack(session[:search_params])
    @imagings = @q.result(distinct: true).order(created_at: :desc).limit(5).records
  
    respond_to do |format|
      format.html
      format.json { render json: @imagings }
    end
  end
end

app/helpers/imagings_helper.rb
module ImagingsHelper
end

app/views/imagings/_checkbox.html.erb
<div class = "condition-checkbox" id="condition">
  <%= form_tag imaging_condition_path(@imaging, @condition, imaging_id: @imaging.id, occupation_id: current_user.occupation_id), method: :delete, id: 'delete-form', data: { confirm: '本当に削除しますか？' } do %>
    <div class="headline"><%= link_to @occupation.name, occupation_path(@occupation)%>の撮影法</div>
    <div class = "condition-all">
      <div class = "condition-table">
      <table border="2" bordercolor="#f0e4e4" height="70" >
        <thead>
          <tr>
            <td align="center">方向</td>
            <td colspan="<%= @occupation.conditions.length %>">撮影法</td>
          </tr>
        </thead>

        <tbody>
          <tr align="center">

            <td>tra</td>
            <% @imaging.conditions.each do |condition| %>
              <% if condition.occupation == @occupation && condition.enhance.id == 1%>
                <% if condition.location.id == 1 && condition.suppression.id == 1%>
                  <td class="contrast" id="contrast-tra-<%= condition.id %>" data-condition-id="<%= condition.id %>">
                    <%= condition.contrast.name %>
                    <%= check_box_tag 'condition_ids[]', condition.id, false, class: 'condition-checkbox', id: "condition-#{condition.id}", style: 'display: none;' %>
                  </td>
                <% elsif condition.location.id == 1 && condition.suppression.id != 1%>
                  <td class="contrast" id="contrast-tra-<%= condition.id %>" data-condition-id="<%= condition.id %>">
                    <%= "#{condition.suppression.name} #{condition.contrast.name}" %>
                    <%= check_box_tag 'condition_ids[]', condition.id, false, class: 'condition-checkbox', id: "condition-#{condition.id}", style: 'display: none;' %>
                  </td>
                <% end %>
              <% end %>
              <% if condition.occupation == @occupation && condition.enhance.id == 2%>
                <% if condition.location.id == 1 && condition.suppression.id == 1%>
                  <td class="contrast" id="contrast-tra-<%= condition.id %>" data-condition-id="<%= condition.id %>">
                    <%= "#{condition.enhance.name} #{condition.contrast.name}" %>
                    <%= check_box_tag 'condition_ids[]', condition.id, false, class: 'condition-checkbox', id: "condition-#{condition.id}", style: 'display: none;' %>
                  </td>
                <% elsif condition.location.id == 1 && condition.suppression.id != 1%>
                  <td class="contrast" id="contrast-tra-<%= condition.id %>" data-condition-id="<%= condition.id %>">
                    <%= "#{condition.enhance.name} #{condition.suppression.name} #{condition.contrast.name}" %>
                    <%= check_box_tag 'condition_ids[]', condition.id, false, class: 'condition-checkbox', id: "condition-#{condition.id}", style: 'display: none;' %>
                  </td>
                <% end %>
              <% end %>
            <% end %>
          </tr>

          <tr align="center">
            <td>cor</td>
            <% @imaging.conditions.each do |condition| %>
              <% if condition.occupation == @occupation && condition.enhance.id == 1%>
                <% if condition.location.id == 2 && condition.suppression.id == 1%>
                  <td class="contrast", id="contrast-cor-<%= condition.id %>"><%= condition.contrast.name%>
                  <%= check_box_tag 'condition_ids[]', condition.id, false, class: 'condition-checkbox', id: "condition_#{condition.id}", style: 'display: none;' %></td>
                <% elsif condition.location.id == 2 && condition.suppression.id != 1%>
                  <td class="contrast", id="contrast-cor-<%= condition.id %>"><%= "#{condition.suppression.name} #{condition.contrast.name}"%>
                  <%= check_box_tag 'condition_ids[]', condition.id, false, class: 'condition-checkbox', id: "condition_#{condition.id}", style: 'display: none;' %></td>
                <% end %>
              <% end %>
              <% if condition.occupation == @occupation && condition.enhance.id == 2%>
                <% if condition.location.id == 2 && condition.suppression.id == 1%>
                  <td class="contrast" id="contrast-tra-<%= condition.id %>" data-condition-id="<%= condition.id %>">
                    <%= "#{condition.enhance.name} #{condition.contrast.name}" %>
                    <%= check_box_tag 'condition_ids[]', condition.id, false, class: 'condition-checkbox', id: "condition-#{condition.id}", style: 'display: none;' %>
                  </td>
                <% elsif condition.location.id == 2 && condition.suppression.id != 1%>
                  <td class="contrast" id="contrast-tra-<%= condition.id %>" data-condition-id="<%= condition.id %>">
                    <%= "#{condition.enhance.name} #{condition.suppression.name} #{condition.contrast.name}" %>
                    <%= check_box_tag 'condition_ids[]', condition.id, false, class: 'condition-checkbox', id: "condition-#{condition.id}", style: 'display: none;' %>
                  </td>
                <% end %>
              <% end %>
            <% end %>
          </tr>
          
          <tr align="center">
            <td>sag</td>
            <% @imaging.conditions.each do |condition| %>
              <% if condition.occupation == @occupation && condition.enhance.id == 1%>
                <% if condition.location.id == 3 && condition.suppression.id == 1%>
                  <td class="contrast", id="contrast-cor-<%= condition.id %>"><%= condition.contrast.name%>
                  <%= check_box_tag 'condition_ids[]', condition.id, false, class: 'condition-checkbox', id: "condition_#{condition.id}", style: 'display: none;' %></td>
                <% elsif condition.location.id == 3 && condition.suppression.id != 1%>
                  <td class="contrast", id="contrast-cor-<%= condition.id %>"><%= "#{condition.suppression.name} #{condition.contrast.name}"%>
                  <%= check_box_tag 'condition_ids[]', condition.id, false, class: 'condition-checkbox', id: "condition_#{condition.id}", style: 'display: none;' %></td>
                <% end %>
              <% end %>
              <% if condition.occupation == @occupation && condition.enhance.id == 2%>
                <% if condition.location.id == 3 && condition.suppression.id == 1%>
                  <td class="contrast" id="contrast-tra-<%= condition.id %>" data-condition-id="<%= condition.id %>">
                    <%= "#{condition.enhance.name} #{condition.contrast.name}" %>
                    <%= check_box_tag 'condition_ids[]', condition.id, false, class: 'condition-checkbox', id: "condition-#{condition.id}", style: 'display: none;' %>
                  </td>
                <% elsif condition.location.id == 3 && condition.suppression.id != 1%>
                  <td class="contrast" id="contrast-tra-<%= condition.id %>" data-condition-id="<%= condition.id %>">
                    <%= "#{condition.enhance.name} #{condition.suppression.name} #{condition.contrast.name}" %>
                    <%= check_box_tag 'condition_ids[]', condition.id, false, class: 'condition-checkbox', id: "condition-#{condition.id}", style: 'display: none;' %>
                  </td>
                <% end %>
              <% end %>
            <% end %>
          </tr>
        </tbody>
      </table>
      </div>
    <div class="condition-delete">
      <%= submit_tag '削除', class: "btn btn-danger delete-conditions", id: 'delete-button', style: "display:none;" %>
    </div>
  <% end %>
</div>


app/views/imagings/_imaging_search.html.erb
<%= form_with(url: search_imagings_path(@imaging, occupation_id: params[:occupation_id]), method: :get, html: {id: "contrast-search-form"}) do |f| %>
<%= render 'shared/error_messages', model: f.object %>

  <div class="headline">信号値から探す</div>

  <table border="2" bordercolor="#f0e4e4" height="70" >
    <div class="signal">
      <tr>
        <td><div class = "signal-headline">高信号</div></td>
        <td><div class = "signal-headline">低信号</div></td>
      </tr>
        
      <tr>
        <td>
          <% @heights.each do |height| %>
            <div class="signal-contrasts">
              <%= f.check_box :height_ids, { multiple: true, style: 'display: none;' }, height.id, nil %>
              <%= height.name %>
            </div>
          <% end %>
        </td>
        <td>
          <% @lows.each do |low| %>
            <div class="signal-contrasts">
              <%= f.check_box :low_ids, { multiple: true, style: 'display: none;' }, low.id, nil %>
              <%= low.name %>
            </div>
          <% end %>
        </td>
      </tr>
    </div>
  </table>
  <%= f.submit "検索", id: "search-submit_btn", class: "search-contrast-btn" %>
<% end %>

<br>
<div id="search-results">
  <div class = "headline">Results:</div>
<div id="search-contrast-results" data-occupation-id="<%= @occupation_id %>">
    <% search_imagings.each do |imaging| %>
      <%= imaging.site.name %><br>
      <%= link_to imaging.purpose, imaging_path(imaging, occupation_id: current_user.occupation.id) %><br><br>
    <% end %>
  </div>
</div>
<br>

app/views/imagings/_other.html.erb
<% if @occupation.conditions.present? %>

<div id="condition">
  <div class="headline"><%= link_to @occupation.name, occupation_path(@occupation)%>の撮影法</div>

  <table border = "2" bordercolor = "#f0e4e4" height= "70">
    <thead>
      <tr>
        <td align="center">方向</td>
        <td colspan = "<%= @occupation.conditions.length %>">撮影法</td>
      </tr>
    </thead>

    <tr align="center">

      <td>tra</td>
      <% @imaging.conditions.each do |condition| %>
        <% if condition.occupation == @occupation && condition.enhance.id == 1%>
          <% if condition.location.id == 1 && condition.suppression.id == 1%>
            <td class = "condition-name"><%= condition.contrast.name%></td>
          <% elsif condition.location.id == 1 && condition.suppression.id != 1%>
            <td class = "condition-name"><%= "#{condition.suppression.name} #{condition.contrast.name}"%></td>
          <% end %>
        <% end %>
        <% if condition.occupation == @occupation && condition.enhance.id == 2%>
          <% if condition.location.id == 1 && condition.suppression.id == 1%>
            <td class = "condition-name"><%= "#{condition.enhance.name} #{condition.contrast.name}"%></td>
          <% elsif condition.location.id == 1 && condition.suppression.id != 1%>
            <td class = "condition-name"><%= "#{condition.enhance.name} #{condition.suppression.name} #{condition.contrast.name}"%></td>
          <% end %>
        <% end %>
      <% end %>
    </tr>

    <tr align="center">
      <td>cor</td>
    <% @imaging.conditions.each do |condition| %>
      <% if condition.occupation == @occupation && condition.enhance.id == 1%>
        <% if condition.location.id == 2 && condition.suppression.id == 1%>
          <td class = "condition-name"><%= condition.contrast.name%></td>
        <% elsif condition.location.id == 2 && condition.suppression.id != 1%>
        <td class = "condition-name"><%= "#{condition.suppression.name} #{condition.contrast.name}"%></td>
        <% end %>
      <% end %>
      <% if condition.occupation == @occupation && condition.enhance.id == 2%>
        <% if condition.location.id == 2 && condition.suppression.id == 1%>
          <td class = "condition-name"><%= "#{condition.enhance.name} #{condition.contrast.name}"%></td>
        <% elsif condition.location.id == 2 && condition.suppression.id != 1%>
          <td class = "condition-name"><%= "#{condition.enhance.name} #{condition.suppression.name} #{condition.contrast.name}"%></td>
        <% end %>
      <% end %>
    <% end %>
  </tr>

    <tr align="center">
      <td>sag</td>
    <% @imaging.conditions.each do |condition| %>
      <% if condition.occupation == @occupation && condition.enhance.id == 1%>
        <% if condition.location.id == 3 && condition.suppression.id == 1%>
          <td class = "condition-name"><%= condition.contrast.name%></td>
        <% elsif condition.location.id == 3 && condition.suppression.id != 1%>
        <td class = "condition-name"><%= "#{condition.suppression.name} #{condition.contrast.name}"%></td>
        <% end %>
      <% end %>
      <% if condition.occupation == @occupation && condition.enhance.id == 2%>
        <% if condition.location.id == 3 && condition.suppression.id == 1%>
          <td class = "condition-name"><%= "#{condition.enhance.name} #{condition.contrast.name}"%></td>
        <% elsif condition.location.id == 3 && condition.suppression.id != 1%>
          <td class = "condition-name"><%= "#{condition.enhance.name} #{condition.suppression.name} #{condition.contrast.name}"%></td>
        <% end %>
      <% end %>
    <% end %>
  </tr>

  </table>
</div>
  <% else %>
    <p>登録された撮影法がありません</p>
  <% end %>

app/views/imagings/_search_results.html.erb
<%= form_with(url: imaging_path(@imaging, occupation_id: @occupation.id), method: :get, html: {id: "contrast-search-form"}) do |f| %>
<%= render 'shared/error_messages', model: f.object %>

  <div class="headline">信号値から探す</div>

  <table border="2" bordercolor="#f0e4e4" height="70" >
    <div class="signal">
      <tr>
        <td><div class = "signal-headline">高信号</div></td>
        <td><div class = "signal-headline">低信号</div></td>
      </tr>
        
      <tr>
        <td>
          <% @heights.each do |height| %>
            <div class="signal-contrasts">
              <%= f.check_box :height_ids, { multiple: true, style: 'display: none;' }, height.id, nil %>
              <%= height.name %>
            </div>
          <% end %>
        </td>
        <td>
          <% @lows.each do |low| %>
            <div class="signal-contrasts">
              <%= f.check_box :low_ids, { multiple: true, style: 'display: none;' }, low.id, nil %>
              <%= low.name %>
            </div>
          <% end %>
        </td>
      </tr>
    </div>
  </table>
  <%= f.submit "検索", id: "search-submit_btn", class: "search-contrast-btn", style: "display:none;" %>
<% end %>

<br>
<div id="search-results">
  <div class = "headline">Results:</div>
<div id="search-contrast-results" data-occupation-id="<%= @occupation_id %>">
    <% search_imagings.each do |imaging| %>
      <%= imaging.site.name %><br>
      <%= link_to imaging.purpose, imaging_path(imaging, occupation_id: current_user.occupation.id) %><br><br>
    <% end %>
  </div>
</div>
<br>

app/views/imagings/_shot.html.erb
<div class="card__body">
<%= link_to "#{@imaging.site.name} #{@imaging.purpose}", imaging_path(@imaging.id), class: :card__title %>
<p class="card__summary">
      <%= @imaging.purpose %>
</p>
</div>

app/views/imagings/_table.html.erb
<% if @occupation.conditions.present? %>
  <%= form_tag imaging_condition_path(@imaging, @condition, imaging_id: @imaging.id, occupation_id: current_user.occupation_id), method: :delete, id: 'delete-form', data: { confirm: '本当に削除しますか？' } do %>

    <div id="condition">
      <h4><%= link_to @occupation.name, occupation_path(@occupation)%>の撮影法</h4>

      <table border="1" bordercolor="#f0e4e4" width="700" height="70">
        <thead>
          <tr>
            <th>tra</th>
            <th>cor</th>
            <th>sag</th>
          </tr>
        </thead>

        <tbody>


<% @imaging.conditions.where(occupation: @occupation).order(Enhance_id: :asc).each do |condition| %>
    <tr>
    <% Location.pluck(:id).each do|i| %>
      <% if condition.location.id == i %>
        <td class="contrast" id="contrast-tra-<%= condition.id %>" data-condition-id="<%= condition.id %>">
        <% if condition.enhance.id == 1 && condition.suppression.id == 1 %>      
          <%= condition.contrast.name %>
        <% elsif condition.enhance.id == 1 && condition.suppression.id != 1 %>
          <%= "#{condition.suppression.name} #{condition.contrast.name}" %>
        <% elsif condition.enhance.id != 1 && condition.suppression.id == 1 %>      
          <%= "#{condition.enhance.name} #{condition.contrast.name}" %>
        <% elsif condition.enhance.id != 1 && condition.suppression.id != 1 %>    
          <%= "#{condition.enhance.name} #{condition.suppression.name} #{condition.contrast.name}" %>
        <% end %>
        <%= check_box_tag 'condition_ids[]', condition.id, false, class: 'condition-checkbox', id: "condition-#{condition.id}", style: 'display: none;' %>
        </td>
      <% else %>
        <td></td>
      <% end %>
    <% end %>
    </tr>
<% end %>

        </tbody>
      </table>
    <%= submit_tag '削除', class: "btn btn-danger delete-conditions", id: 'delete-button', style: "display:none;" %>
  <% end %>
<% end %>


app/views/imagings/index.html.erb
<% if current_user.id == 1 %>
  <%= link_to '施設検索', occupations_path %>
  <%= link_to '問い合わせ確認', contacts_path %>
<% end %>
index
<br>
<br>
<%= link_to 'お問い合わせ', new_contact_path %>
<br>
<br>
コミュニケーションツール
<br>
掲示板や質問、画像、いいね、ブロック、公開非公開（）
<br>
<br>
<br>

app/views/imagings/search.html.erb
<script>
  const occupationId = <%= @occupation&.id || '' %>;
</script>

<%= form_with(url: search_imagings_path, method: :get, html: { id: "contrast-search-form" }) do |f| %>
  <div class="headline">信号値から探す</div>

  <table border="2" bordercolor="#f0e4e4" height="70">
    <div class="signal">
      <tr>
        <td><div class="signal-headline">高信号</div></td>
        <td><div class="signal-headline">低信号</div></td>
      </tr>
        
      <tr>
        <td>
          <% @heights.each do |height| %>
            <div class="signal-contrasts">
              <%= f.check_box :height_ids, { multiple: true, style: 'display: none;', onchange: 'performSearch();' }, height.id, nil %>
              <%= height.name %>
            </div>
          <% end %>
        </td>
        <td>
          <% @lows.each do |low| %>
            <div class="signal-contrasts">
              <%= f.check_box :low_ids, { multiple: true, style: 'display: none;', onchange: 'performSearch();' }, low.id, nil %>
              <%= low.name %>
            </div>
          <% end %>
        </td>
      </tr>
    </div>
  </table>
  <%= f.submit "検索", id: "search-submit-btn", class: "search-contrast-btn", style: 'display: none;' %>
<% end %>


<br>
<div id="search-results">
  <div class = "headline">Results:</div>
    <div id="search-contrast-results" data-occupation-id="<%= @occupation_id %>">
      <%= render @search_imagings %>
    </div>
  </div>
<br>

app/views/imagings/show.html.erb
<%= @occupation.name %>
<div class="imaging-all">
  <div class="imaging-main">
    <div class="headline">
      検査目的
    </div>
      <%= link_to "#{@imaging.site.name} #{@imaging.purpose}", edit_imaging_path(@imaging) %>
    <div class="imaging-table">
      <div class="imaging-headline">
        <table border = "2" bordercolor = "#f0e4e4" >
          <tr>
            <td>主な症状</td>
            <td><%= @imaging.symptoms %></td>
          </tr>
          <tr>
            <td>主な治療法</td>
            <td><%= @imaging.treatment %></td>
          </tr>
          <tr>
            <td>画像所見</td>
            <td><%= @imaging.identification %></td>
          </tr>
          <tr>
            <td>備考</td>
            <td><%= @imaging.comment %></td>
          </tr>
        </table>
        <br>
        <table border = "2" bordercolor = "#f0e4e4" >
          <tr>
            <td class = "signal-table">高信号</td>
            <% @imaging.heights.each do |height| %>
              <td class = "signal-table"><%= height.name %></td>
            <% end %>
          </tr>
          <tr>
            <td class = "signal-table">低信号</td>
            <% @imaging.lows.each do |low| %>
              <td class = "signal-table"><%= low.name %></td>
            <% end %>
          </tr>
        </table>
      </div>

      <% if current_user.id == 1 %>
        <%= link_to '削除', imaging_path, method: :delete %>
      <% end %>
      <br>
    </div>
  </div>
  <div class = "condition-register">
  <br>
    <div class="side-headline">
    撮影法の登録
    </div>
    <% if current_user.occupation.present? %>
    <div class="condition-form">
      <%= render 'conditions/condition', occupation: @occupation %>
    </div>
    <% else %>
      <br>
      所属施設の登録が<br>必要です<br><br>
      <div class="side-registration">
      <%= link_to '所属施設登録', occupations_path, class: "registration-text" %>
      </div>
    <% end %>
  </div>


<div class = "condition-table">
  <% if @occupation == current_user.occupation %>
    <%= render "checkbox" %><br>
    <% if @remark.present? %>
      <%= "備考： #{@remark.content}" %>
      <%= link_to '編集', edit_imaging_remark_path(@imaging, current_user.occupation) %>
      <%= link_to '削除', imaging_remark_path(@imaging, current_user.occupation), method: :delete %>
    <% else %>
      <%= link_to '備考登録', new_imaging_remark_path(@imaging, current_user.occupation) %>
    <% end %>
  <% else %>
    <%= render "other" %><br>
  <% end %>

  <div class="headline">
  他施設の撮影法を見る
  </div>

  <% if current_user.occupation.present? %>
    <% @occupations.where.not(id: [current_user.occupation.id, @occupation.id]).each do |occupation| %>
      <%= link_to occupation.name, imaging_path(@imaging, occupation_id: occupation.id) %>
    <% end %>
  <% else %>
    <% @occupations.where.not(id:  @occupation.id).each do |occupation| %>
      <%= link_to occupation.name, imaging_path(@imaging, occupation_id: occupation.id) %>
    <% end %>
  <% end %>
  <br>
  <br>

  <% if current_user.occupation.present? && @occupation != current_user.occupation %>
    <%= link_to '自施設の撮影法', imaging_path(@imaging, occupation_id: current_user.occupation.id)%>
  <% end %>
</div>

  <div class="headline">
  施設検索
  </div>
  <%= render "occupations/search_form" %><br>
</div>