config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  root to: 'imagings#index'
  resources :imagings do
    collection do
      match 'search', via: [:get, :post]
    end
    resources :conditions, only: [:new, :create, :show, :edit, :update, :destroy] do
      member do
        put 'toggle_checkbox'
      end
      collection do
        delete 'destroy_selected'
      end
    end
    resources :remarks, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :users, only: :show
  resources :occupations do
    resources :machines, only: [:new, :create, :show, :edit, :update, :destroy]
    resources :occupation_memberships, only: [:index, :new, :show, :create, :destroy] do
      member do
        patch 'accept'
        patch 'reject'
      end
    end
    collection do
      get :search
    end
  end
  post '/occupations/search', to: 'occupations#search'
  delete 'occupations/:id/leave', to: 'occupations#leave', as: :leave_occupation

  resources :contacts, only: [:index, :new, :create, :destroy] do
    patch :update_visibility, on: :collection
  end
  get 'contact_thanks', to: 'contacts#thanks', as: 'contact_thanks'

  #resources :categories, only: [:index, :new, :create]
  #get '/category/:id', to: 'categories#search'
end

app/models/occupation.rb
class Occupation < ApplicationRecord
    has_many :users, dependent: :nullify
    has_many :occupation_machines, dependent: :destroy
    has_many :machines, through: :occupation_machines, dependent: :destroy
    has_many :conditions, dependent: :destroy
    has_many :occupation_memberships, dependent: :destroy
    has_one  :remark, dependent: :destroy
    
  before_destroy :destroy_if_no_users

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture1

    with_options presence: true do
      validates :name
      validates :post_code, format: { with: /\A[0-9]{3}-[0-9]{4}\z/, message: 'is invalid. Include hyphen(-)' }
      validates :prefecture1_id, numericality: {other_than: 0, message: "can't be blank"}
      validates :phone_number, uniqueness: true, format: { with: /\A\d{10,11}\z/, message: 'is invalid' }, length: { maximum: 11 }
    end

  def self.search_by_name(name)
    where('name LIKE ?', "%#{name}%")
  end
  
  private

  def destroy_if_no_users
    destroy if users.count.zero?
  end
end

app/controllers/occupations_controller.rb
class OccupationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_occupation, only: [:show, :edit, :update, :destroy]
  before_action :set_not_admin, only: [:show, :edit, :update, :destroy]
  skip_before_action :set_search_query, only: [:search]

  def index
    @occupation = Occupation.all
  end
  
  def new
    @occupation = Occupation.new
  end
  
  def create
    @occupation = Occupation.new(occupation_params)
    if @occupation.valid?
      @occupation.save
      current_user.update_columns(occupation_id: @occupation.id)
      flash[:success] = "所属施設を登録しました。"
      redirect_to occupation_path(@occupation)
    else
      render :new
    end
  end

  def show
    @users = @occupation.users
    @conditions = @occupation.conditions.select(:imaging_id).distinct
    @imgs = @conditions.map(&:imaging)
    @machine = Machine.find_by(params[id: @machine_id])
    @machines = @occupation.machines
  end

  def edit
  end

  def update
    if @occupation.valid?
      @occupation.update(occupation_params)
      redirect_to occupation_path(@occupation)
    else
      render :new
    end
  end
  
  def destroy
    if @occupation == current_user.occupation || current_user.id == 1
      @occupation.conditions.destroy_all
      @occupation.occupation_machines.destroy_all
      # @occupation を参照している users レコードを取得して削除する
      User.where(occupation_id: @occupation.id).update_all(occupation_id: nil)
      # @occupation を参照している machines レコードを取得して削除する
      Machine.where(occupation_id: @occupation.id).destroy_all
      
      @occupation.destroy
      @occupation = Occupation.find_by(name: "未登録")
      redirect_to root_path
    else
      render :show
    end
  end

  def search
    prefecture1_id = params[:prefecture1_id]
    phone_number = params[:phone_number]
    name = params[:name]
    @occupations = Occupation.all
    
    # 検索条件が指定されている場合には条件を追加する
    @occupations = @occupations.where(prefecture1_id: prefecture1_id) if prefecture1_id.present?
    @occupations = @occupations.where(phone_number: phone_number) if phone_number.present?
    @occupations = @occupations.where("name LIKE ?", "%#{name}%") if name.present?
    
    respond_to do |format|
      format.json { render json: @occupations }
      format.html
    end
  end

  def leave
    @occupation = Occupation.find(params[:id])
    
    if current_user.occupation == @occupation
      current_user.update_columns(occupation_id: nil)
      flash[:success] = '脱退しました。'
      if @occupation.users.count.zero?
        @occupation.destroy
        flash[:notice] = 'Occupationが削除されました。'
        redirect_to root_path
      else
        redirect_to occupation_path(id: @occupation.id)
      end
    else
      flash[:error] = '脱退に失敗しました。'
      redirect_to occupation_path(id: @occupation.id)
    end
  end
  
  
  
  private

  def occupation_params
    params.require(:occupation).permit(:name, :post_code, :prefecture1_id, :municipality, :address, :building_name, :phone_number)
  end

  def set_occupation
    @occupation = Occupation.find(params[:id])
  end

  def set_not_admin
    if current_user.occupation.present?
      if current_user.occupation.id !=1 && (@occupation.id == 1 || @occupation.id == 2)
        redirect_to root_path
        return
      end
    else
      if @occupation.id == 1 || @occupation.id == 2
        redirect_to root_path
        return
      end
    end
  end
end


#@occupations = Occupation.find(params[:id])
#@imaging = Imaging.find(params[:id])
#@occupation = Occupation.includes(conditions: :imaging).find(params[:id])
#@condid = Condition.select(:imaging_id).distinct

app/helpers/occupations_helper.rb
module OccupationsHelper
end

app/views/occupations/_search_form.html.erb
<%= form_with(url: search_occupations_path, method: :get, remote: true, id: "search-occupation") do |form| %>
  <%= form.collection_select :prefecture1_id, Prefecture1.all, :id, :name, {include_blank: "---"}, class: "condition-contrast" %>
  <%= form.text_field :phone_number, placeholder: 'phone number', class: "condition-contrast" %>
  <%= form.text_field :name, placeholder: 'name', class: "condition-contrast", autocomplete: "off" %>
  <%= form.submit 'Search', class: "search-occupation-btn", id: "search-occupation-btn" %>
<% end %>

<div id="search-occupation-results">
</div>

app/views/occupations/edit.html.erb
<div class="contents-all">
<%= form_with model: @occupation, class: 'registration-main', local: true do |f| %>
<%= render 'shared/error_messages', model: f.object %>

<div class='form-wrap'>
  <div class='form-header'>
    <div class='headline'>
      所属施設情報の編集
    </div>
  </div>

  <%= render 'shared/error_messages', model: f.object %>

<p>所属施設</p>
  <div class="form-group">
    <div class='form-text-wrap'>
          <label class="form-text", for="post-code" >郵便番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :post_code, class:"input-default", id:"post-code", placeholder:"例）123-4567", maxlength:"8" %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text", for="prefecture">都道府県</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.collection_select(:prefecture1_id, Prefecture1.all, :id, :name, {include_blank: "---"}, {class:"select-box", id:"prefecture"}) %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text", for="occupation-name">施設名</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :name, class:"input-default", id:"occupation-name", maxlength:"40" %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
          <label class="form-text", for= "phone-number">電話番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :phone_number, class:"input-default", id:"phone-number", placeholder:"例）0123456789", maxlength:"11" %>
  </div>

  <div class='register-btn'>
    <%= f.submit "編集" , class: "registration-text" %>
  </div>
</div>
<% end %>

</div>

app/views/occupations/index.html.erb

    <%= render "search_form" %><br>

app/views/occupations/new.html.erb
<div class="contents-all">
<%= form_with model: @occupation, class: 'registration-main', local: true do |f| %>
<%= render 'shared/error_messages', model: f.object %>

<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      所属施設登録
    </h1>
  </div>

  <%= render 'shared/error_messages', model: f.object %>

<p>所属施設</p>
  <div class="form-group">
    <div class='form-text-wrap'>
          <label class="form-text", for="post-code" >郵便番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :post_code, class:"input-default", id:"post-code", placeholder:"例）123-4567", maxlength:"8" %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text", for="prefecture">都道府県</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.collection_select(:prefecture1_id, Prefecture1.all, :id, :name, {include_blank: "---"}, {class:"select-box", id:"prefecture"}) %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text", for="occupation-name">施設名</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :name, class:"input-default", id:"occupation-name", placeholder:"例) 日本病院", maxlength:"40" %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
          <label class="form-text", for= "phone-number">電話番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :phone_number, class:"input-default", id:"phone-number", placeholder:"例）0123456789", maxlength:"11" %>
  </div>

  <div class='register-btn'>
    <%= f.submit "登録" , class: "registration-text" %>
  </div>
</div>
<% end %>

</div>

app/views/occupations/search.html.erb
<% if @occupations.present? %>
  <table>
    <thead>
      <tr>
        <th>Prefecture</th>
        <th>Phone Number</th>
        <th>Name</th>
      </tr>
    </thead>
    <tbody>
      <% @occupations.each do |occupation| %>
        <tr>
          <td><%= occupation.prefecture1.name %></td>
          <td><%= occupation.phone_number %></td>
          <td><%= link_to occupation.name, occupation_path(occupation) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>まだその施設はありません</p>
  <%= link_to '登録する', new_occupation_path, class: "registration-text" %>
<% end %>

app/views/occupations/show.html.erb
<div class="contents-all">

<div class = "headline">施設名</div>
<div>
  <%= @occupation.name%>
</div>

      <% if current_user.occupation.nil? %>
        <% if current_user.occupation_memberships.exists?(occupation_id: @occupation.id) %>
          <% membership = current_user.occupation_memberships.find_by(occupation_id: @occupation.id) %>
          
    <% if membership.status == "rejected" %>
      <p>申請が拒否されました</p>
      <% membership.update(status: "pending") %> <!-- 状態を "pending" に戻す -->
    <% end %>
    
    <div class="side-registration">
      <% if current_user.occupation_memberships.where(occupation_id: @occupation.id, status: "pending").exists? %>
        <%= link_to '申請を取り消す', occupation_occupation_membership_path(membership), method: :delete, data: { confirm: '本当に申請を取り消しますか？' }, class: "registration-text" %>
      <% else %>
        <%= link_to '申請する', occupation_occupation_memberships_path(user_id: current_user.id, occupation_id: @occupation.id), method: :post, class: "registration-text" %>
      <% end %>
    </div>
  <% else %>
    <div class="side-registration">
      <%= link_to '申請する', occupation_occupation_memberships_path(user_id: current_user.id, occupation_id: @occupation.id), method: :post, class: "registration-text" %>
    </div>
  <% end %>
<% elsif @occupation.occupation_memberships.exists?(occupation_id: @occupation.id, status: "pending") %>
  <%= link_to '申請があります', occupation_occupation_memberships_path(occupation_id: @occupation.id), class: "registration-text" %>
<% end %>

      <% if flash[:success] %>
        <div class="flash-message flash-success">
          <%= flash[:success] %>
        </div>
      <% elsif flash[:error] %>
        <div class="flash-message flash-error">
          <%= flash[:error] %>
        </div>
      <% end %>

<div class='nav'>
<% if current_user.occupation == @occupation %>
  <ul class='lists-right'>
    <li><%= link_to '編集', edit_occupation_path(@occupation), class: "occupation-edit" %></li>
    <li><%= link_to '削除', occupation_path(@occupation), method: :delete, class: "occupation-edit", data: { confirm: '本当に削除しますか？' } %></li>
  </ul>
<% end %>
</div>

<div class = "headline">
  使用機器
</div>

<% if @occupation.machines.present? %>
  <table>
    <thead>
      <tr>
        <th>メーカー</th>
        <th>磁場強度</th>
        <th>装置名</th>
      </tr>
    </thead>
    <tbody>
      <% @occupation.machines.each do |machine| %>
        <tr>              
          <td><%= machine.manufacturer.name %></td><br>
          <td><%= machine.strength.name %></td><br>
          <td><%= link_to machine.name, occupation_machine_path(machine, occupation_id: @occupation.id) %></td><br><br>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <% if @occupation == current_user.occupation %>
    <%= link_to "使用機器の追加", new_occupation_machine_path(occupation_id: @occupation.id) %>
  <% end %>
  <% else %>
  未登録
  <% if @occupation == current_user.occupation %>
    <%= link_to "新規登録", new_occupation_machine_path(@machine, occupation_id: @occupation.id) %>
  <% end %>
<% end %>

<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <div class = "headline">
        <%= "#{@occupation.name}のメンバー"%>
      </div>
      <% if @occupation.users.present? %>
        <% @occupation.users.each do |user| %>
        <div>
          <%= link_to user.nickname, user_path(user) %>
        </div>
      <% end %>

        <% else %>
        <p>所属しているユーザーがいません</p>
      <% end %>

      <% if current_user.occupation == @occupation %>
        <%= link_to '脱退する', leave_occupation_path(@occupation), method: :delete, data: { confirm: '本当に脱退しますか？' }, class: "registration-text" %>
      <% end %>

        <table>
      <div class = "headline">
        登録している撮影法
      </div>
            <% if @occupation.conditions.present? %>
            <tr>
              <th>部位</th>
              <th>検査目的</th>
            </tr>
              <% @imgs.each do |imaging| %>
                <tr>              
                  <td><%= imaging.site.name %></td><br>
                  <td><%= link_to imaging.purpose, imaging_path(imaging, occupation_id: @occupation.id) %></td><br><br>
                </tr>
              <% end %>
            <% else %>
              <p>撮影条件の登録はありません</p>
            <% end %>
        </table>
      </div>
    </div>
</div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<% if current_user.id == 1 %>
  <ul class='lists-right'>
    <li><%= link_to 'この施設を削除', occupation_path(@occupation), method: :delete, class: "occupation-edit", data: { confirm: '本当に削除しますか？' } %></li>
  </ul>
<% end %>