config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  root to: 'imagings#index'
  resources :imagings do
    collection do
      match 'search', via: [:get, :post]
    end
    resources :conditions, only: [:new, :create, :show, :edit, :update, :destroy] do
      member do
        put 'toggle_checkbox'
      end
      collection do
        delete 'destroy_selected'
      end
    end
    resources :remarks, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :users, only: :show
  resources :occupations do
    resources :machines, only: [:new, :create, :show, :edit, :update, :destroy]
    resources :occupation_memberships, only: [:index, :new, :show, :create, :destroy] do
      member do
        patch 'accept'
        patch 'reject'
      end
    end
    collection do
      get :search
    end
  end
  post '/occupations/search', to: 'occupations#search'
  delete 'occupations/:id/leave', to: 'occupations#leave', as: :leave_occupation

  resources :contacts, only: [:index, :new, :create, :destroy] do
    patch :update_visibility, on: :collection
  end
  get 'contact_thanks', to: 'contacts#thanks', as: 'contact_thanks'

  #resources :categories, only: [:index, :new, :create]
  #get '/category/:id', to: 'categories#search'
end

app/models/occupation_membership.rb
class OccupationMembership < ApplicationRecord
  belongs_to :user
  belongs_to :occupation

  validates :user_id, presence: true
  validates :occupation_id, presence: true
  validate :check_duplicate_membership, unless: :rejected?

  def check_duplicate_membership
    if self.class.exists?(user_id: user_id, occupation_id: occupation_id, status: 'pending')
      errors.add(:user_id, 'は既に申請済みです。') unless status == 'accepted'
    end
  end

  def rejected?
    status == 'rejected'
  end


  enum status: {
    pending: 'pending',
    approved: 'approved',
    accepted: 'accepted',
    rejected: 'rejected'
  }
end

app/controllers/occupation_memberships_controller.rb
class OccupationMembershipsController < ApplicationController

  def index
    @user = User.all
    @occupation = Occupation.find(params[:occupation_id])
    @pending_memberships = @occupation.occupation_memberships.pending
  end

  def create
    @membership = OccupationMembership.new(user_id: params[:user_id], occupation_id: params[:occupation_id])

    if @membership.save
      flash[:success] = '申請が送信されました。'
    else
      flash[:error] = '申請の送信に失敗しました。'
    end

    redirect_to occupation_path(params[:occupation_id])
  end

  def destroy
    @occupation = Occupation.find(params[:id])
    @membership = OccupationMembership.find_by(user_id: current_user.id, occupation_id: @occupation.id)
    @membership.destroy
    flash[:success] = '申請が取り消されました。'
    redirect_to occupation_path(@occupation)
  end

  def accept
    @membership = OccupationMembership.find(params[:id])
    @occupation = @membership.occupation
    
    if @membership.pending?
      @membership.user.update_columns(occupation_id: @occupation.id)
      if @membership.user.errors.any?
        puts @membership.user.errors.full_messages
      end
      @membership.update(status: "accepted")
      flash[:notice] = "申請を承認しました。"
    else
      flash[:error] = "無効な操作です。"
    end
    redirect_to occupation_occupation_memberships_path
  end

  def reject
    @membership = OccupationMembership.find(params[:id])
    @membership.rejected!
    redirect_to occupation_occupation_memberships_path, notice: '申請を拒否しました。'
  end
end

app/helpers/occupation_memberships_helper.rb
module OccupationMembershipsHelper
end

app/views/occupation_memberships/index.html.erb
<div class="pending-memberships">
  <% if @pending_memberships.any? %>
    <div>申請一覧</div>
    <ul>
      <% @pending_memberships.each do |membership| %>
        <% next unless membership.occupation_id == current_user.occupation.id %> <!-- 自施設以外の申請をスキップ -->
        <li>
          <%= link_to membership.user.nickname, user_path(membership.user.id) %>さんからの申請
          <%= link_to '承認', accept_occupation_occupation_membership_path(@occupation, membership), method: :patch %>
          <%= link_to '拒否', reject_occupation_occupation_membership_path(@occupation, membership), method: :patch %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>現在、申請はありません</p>
  <% end %>
</div>

app/views/occupation_memberships/new.html.erb
<h1>New Occupation Membership</h1>
<%= form_with(model: @occupation_membership, url: occupation_occupation_memberships_path) do |form| %>

  <div>
    <%= form.label :occupation_id %>
    <%= form.collection_select :occupation_id, Occupation.all, :id, :name, {include_blank: "---"}, class: "condition-contrast" %>
  </div>
  <div>
    <%= form.submit 'Create Occupation Membership' %>
  </div>
<% end %>

app/views/occupation_memberships/show.html.erb
<h1>Occupation Membership Details</h1>
<p>User: <%= @occupation_membership.user.name %></p>
<p>Occupation: <%= @occupation_membership.occupation.name %></p>
<p>Joined at: <%= @occupation_membership.created_at %></p>