config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  root to: 'imagings#index'
  resources :imagings do
    collection do
      match 'search', via: [:get, :post]
    end
    resources :conditions, only: [:new, :create, :show, :edit, :update, :destroy] do
      member do
        put 'toggle_checkbox'
      end
      collection do
        delete 'destroy_selected'
      end
    end
    resources :remarks, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :users, only: :show
  resources :occupations do
    resources :machines, only: [:new, :create, :show, :edit, :update, :destroy]
    resources :occupation_memberships, only: [:index, :new, :show, :create, :destroy] do
      member do
        patch 'accept'
        patch 'reject'
      end
    end
    collection do
      get :search
    end
  end
  post '/occupations/search', to: 'occupations#search'
  delete 'occupations/:id/leave', to: 'occupations#leave', as: :leave_occupation

  resources :contacts, only: [:index, :new, :create, :destroy] do
    patch :update_visibility, on: :collection
  end
  get 'contact_thanks', to: 'contacts#thanks', as: 'contact_thanks'

  #resources :categories, only: [:index, :new, :create]
  #get '/category/:id', to: 'categories#search'
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='nav'>
    <% if user_signed_in? %>
        <%= link_to "MRI guide", root_path(id: current_user.id), class: "header-title" %>
      <ul class='lists-header'>
        <div class="header-user">
          <li><%= link_to current_user.nickname, user_path(id: current_user.id), class: "header-nickname" %></li>
          <% if current_user.occupation.present? %>
            <li><%= link_to current_user.occupation.name, occupation_path(current_user.occupation.id), class: "header-occupation" %></li>
          <% else %>
            <li><%= link_to '所属施設登録', occupations_path, class: "header-occupation" %></li>
          <% end %>
        <div class="menu-icon">
          <div class="menu">
            <li><%= button_to search_imagings_path, method: :get, class: "header-dropdown", form_class: "link-button" do %>
              信号値で検索
            <% end %></li>
            <li><%= button_to occupations_path, method: :get, class: "header-dropdown", form_class: "link-button" do %>
              施設検索
            <% end %></li>
            <li><%= button_to destroy_user_session_path, method: :delete, class: "header-dropdown", form_class: "link-button" do %>
              ログアウト
            <% end %></li>
          </div>
        </div>

      </div>
    <% else %>
      <div class = "devise-header">
        <div class= "devise-title">
        MRI guide
      </div>
      </div>
    <% end %>
  </div>
</header>

app/views/shared/_side_bar.html.erb
<div class="header_name">
  <div class='item-contents' id="detailed-search-result-wrapper">
    <br>
    <% if user_signed_in? && !((controller_name == 'occupations' && (action_name == 'index' || action_name == 'search')) || (controller_name == 'imagings' && action_name == 'search') || (action_name == 'new' || action_name == 'edit') || controller_name == 'contacts') %>
      <script>
        const occupationId = <%= @occupation&.id || current_user&.occupation&.id || '' %>;
      </script>

      <div class="side-headline">検索</div>
      <%= search_form_for @q, url: imagings_path, remote: true, html: { id: "detailed-search-form" } do |f| %>
        <div class="search-field">
          <%= f.label :site_id_eq, '部位', for: "search-site" %>
          <br>
          <%= f.collection_select(:site_id_eq, Site.all, :id, :name, { include_blank: "---" }, class: "search-site", id: "search-site") %>
        </div>
        <br>
        <div class="search-field">
          <%= f.label :purpose_cont, '検査目的', for: "search-purpose" %>
          <br>
          <%= f.text_field :purpose_cont, placeholder: '', value: params[:q]&.dig(:purpose_cont), class: "search-purpose", id: "search-purpose" %>
        </div>
        <br>
        <%= f.submit '検索', class: "search-button1" %>
      <% end %>

      <ul class='item-lists' id="detailed-search-result" data-occupation-id="<%= @occupation.id %>">
        <% @imagings.each do |imaging| %>
          <li class='list'>
            <div class="posted-content">
              <%= imaging.site.name %><br>
              <% if current_user.occupation.present? %>
                <%= link_to imaging.purpose, imaging_path(imaging, occupation_id: current_user.occupation.id), class: "search-result" %><br><br>
              <% else %>
                <%= link_to imaging.purpose, imaging_path(imaging), class: "search-result" %><br><br>
              <% end %>
            </div>
          </li>
        <% end %>
      </ul>

      <div class="side-register">
        <% if current_user.occupation.present? %>
          <div class="side-registration">
            <%= link_to '新規登録', new_imaging_path(q: @q), id: "imaging-register", class: "registration-text" %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>